version: '3.8'

services:
  twin:
    build: .
    container_name: twin_app
    env_file:
      - .env
    # Use host network to simplify networking for RTSP
    network_mode: host
    # No need for audio devices with RTSP
    # devices:
    #   - /dev/snd:/dev/snd
    # No need for PulseAudio with RTSP
    # volumes:
    #   - /run/user/$$(id -u)/pulse/native:/run/user/1000/pulse/native 
    #   - ~/.config/pulse/cookie:/home/appuser/.config/pulse/cookie
    volumes:
      # Mount application-specific persistent volumes
      - ./reports:/app/reports
      - ./logs:/app/logs
    environment:
      # Set audio source to RTSP explicitly
      - AUDIO_SOURCE=rtsp
      # Target host for SSH commands (sound playback and media control)
      - SSH_HOST_TARGET=andy@192.168.1.43
    restart: always
    # Pass necessary arguments
    command: [
      "python", "main.py", 
      "--remote-inference", "http://192.168.1.40:11434/api/generate",
      "--remote-transcribe", "http://192.168.1.40:8123",
      "--remote-store", "http://192.168.1.40:5050/vectorstore",
      "-e"
    ] 