version: '3.8'

services:
  # RTSP Server (mediamtx)
  rtsp-server:
    image: bluenviron/mediamtx:latest
    container_name: rtsp-server
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./mediamtx.yml:/mediamtx.yml:ro

  # Single RTSP Client - pushes mic audio to rtsp-server
  rtsp-client:
    build:
      context: .
      dockerfile: Dockerfile.rtsp-client
    container_name: rtsp-client-mic
    environment:
      - RTSP_SERVER_IP=${RTSP_SERVER_IP:-127.0.0.1}
      - RTSP_SERVER_PORT=${RTSP_SERVER_PORT:-8554}
      - STREAM_PATH=mic
      - AUDIO_DEVICE=${AUDIO_DEVICE:-default}
      - SAMPLE_RATE=${SAMPLE_RATE:-16000}
      - CHANNELS=${CHANNELS:-1}
    volumes:
      - /dev/snd:/dev/snd:rw  # Audio devices
      - /run/user/1000/pulse:/run/user/1000/pulse:rw  # PulseAudio socket
      - /etc/pulse:/etc/pulse:ro  # PulseAudio config
      - /home/${USER:-1000}/.config/pulse:/home/rtspuser/.config/pulse:ro  # User PulseAudio config
    network_mode: host  # Use host networking for audio
    restart: unless-stopped
    user: "1000:1000"  # Use fixed user ID instead of environment variables

networks:
  default:
    name: rtsp-client-network
